/* 
If set A = {L M N O P} and set B = {P Q R S T}, 
what sets are generated by the following operations?

- A union B
- A union all B
- A intersect B
- A except B
*/

-- A union B:      LMNOPQRST
-- A union all B:  LMNOPPQRST 
-- A intersect B:  P
-- A except B:     LMNOQRST   

/* Reflections here - made I mistake at:
- A except B:     LMNOQRST

the actual answer is  LMNO
The reason is that the complete set B is being removed
from the result. Not only the matching element. Remember this.
*/

